version: '3'

services:
  drf:
    build:
      context: .
      dockerfile: docker/dev/python/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
