version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  static_files:

services:
  drf:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    command: gunicorn -w 4 config.wsgi -b 0.0.0.0:8000 --timeout 90 --log-level debug --access-logfile - --error-logfile -
    volumes:
      - .:/code
      - static_files:/static_files
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres
    depends_on:
      - nginx
    restart: always
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 8081:8081
    restart: always
  nginx-proxy:
    build:
      context: .
      dockerfile: docker/prod/nginx/nginx-proxy/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 80:80
    restart: always
