name: Production deploy

on:
  push:
    branches: [ prod, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Production deployment
    steps:
    - name: SSH
      uses: fifsky/ssh-action@master
      with:
        command: |
          echo 'Connected to server, starting deployment'
          cd Fees
          sh -x ./docker/deploy.sh prod.yml
        host: ${{ secrets.PRODUCTION_IP }}
        user: ubuntu
        key: ${{ secrets.PRODUCTION_PRIVATE_KEY}}
        args: "-tt -vvv"
